image:
  - Visual Studio 2017

environment:
  NodeVersion: 9
  BuildDirectory: build
  Generator: Visual Studio 15 2017 Win64
  DistributeDirectory: distribute
  FullDistributePath: $(SLBuildDirectory)\$(SLDistributeDirectory)
  DistributionAritfact: $(RuntimeName)-$(RuntimeVersion)-node-fontinfo

install:
  - ps: Install-Product node $env:NodeVersion x64
  - npm install

build_script:
  - cmd: ci\win-build.cmd
  - tar cvaf "%DistributionAritfact%.tar.gz" -C "%FullDistributePath%" "node-fontinfo"

before_deploy:
  - ps: Push-AppveyorArtifact "$env:DistributionAritfact.tar.gz"

deploy:
  - provider: GitHub
    artifact: $(DistributionAritfact).tar.gz
    auth_token:
      secure: nP2TonQxdUNyL65bmBKVPi0/jYX3h6mPCdFgJs1WeD+kNhgoUJ4mqxZ2FWkjpE0N
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true

artifacts:
  - path: $(DistributionAritfact).tar.gz
    name: Distribution Aritfact

test: off